### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmaxguard.so" not found

### ISSUE THREAD

**Issue by thefaisalurrehman** [farimarwat/maxguard#1]
```
FATAL EXCEPTION: main
Process: com.???..., PID: 7871
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmaxguard.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1656)
	at com.farimarwat.maxguard.MaxGuard.<clinit>(Unknown Source:2)
	at com.example.??.ui.activities.MainActivity.onCreate(Unknown Source:3)
	at android.app.Activity.performCreate(Activity.java:8050)
	at android.app.Activity.performCreate(Activity.java:8030)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003).
```
	
	**I face this issue in prelaunch report from Google Play Console**

**Comment by farimarwat** [comment]
I was using filterabi to only allow arm64 and excluded x86, x86_64 in gradle because it will maximize the security. Now removed and fixed the bug.

**Comment by Micoder-dev** [comment]
> I was using filterabi to only allow arm64 and excluded x86, x86_64 in gradle because it will maximize the security. Now removed and fixed the bug.

I also got this same crash report in a release from Firebase Crashlystics today! I think still it not fixed

**Comment by farimarwat** [comment]
> > I was using filterabi to only allow arm64 and excluded x86, x86_64 in gradle because it will maximize the security. Now removed and fixed the bug.
> 
> I also got this same crash report in a release from Firebase Crashlystics today! I think still it not fixed

Kindly update to version 1.2

**Comment by tikaydev** [comment]
Version 1.2 fixed the above issue but is not 16KB aligned. I updated to version 1.3 

> > > I was using filterabi to only allow arm64 and excluded x86, x86_64 in gradle because it will maximize the security. Now removed and fixed the bug.
> > 
> > 
> > I also got this same crash report in a release from Firebase Crashlystics today! I think still it not fixed
> 
> Kindly update to version 1.2

Version 1.2 fixed the above issue but is not 16KB aligned. I updated to version 1.3 and had this same bug. Kindly fixed. Thanks again for this great library.


                       
                        java.lang.UnsatisfiedLinkError: dlopen failed: library "libmaxguard.so" not found
                        	at java.lang.Runtime.loadLibrary0(Runtime.java:1090)
                        	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
                        	at java.lang.System.loadLibrary(System.java:1765)
                        	at com.farimarwat.maxguard.MaxGuard.<clinit>(MaxGuard.kt:17)
                        	at com.traytontech.homitv.MainActivity.onCreate(MainActivity.kt:87)
                        	at android.app.Activity.performCreate(Activity.java:9155)
                        	at android.app.Activity.performCreate(Activity.java:9133)
                        	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1521)
                        	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4262)
                        	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4467)
                        	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:222)
                        	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
                        	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
                        	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
                        	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2823)
                        	at android.os.Handler.dispatchMessage(Handler.java:110)
                        	at android.os.Looper.loopOnce(Looper.java:248)
                        	at android.os.Looper.loop(Looper.java:338)
                        	at android.app.ActivityThread.main(ActivityThread.java:9067)
                        	at java.lang.reflect.Method.invoke(Native Method)
                        	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)`

**Comment by farimarwat** [comment]
do you mean the issue again appeared in 1.3?
Could you please share the testing device CPU architecture? or it will be better to send full specification of the device

**Comment by tikaydev** [comment]
> do you mean the issue again appeared in 1.3? Could you please share the testing device CPU architecture? or it will be better to send full specification of the device

Yes it appeared in version 1.3

Pixel 9a  Emulator
API Level:  36
ABI/CPU:  x86_64

@farimarwat I analysed the generated APK and realized **libmaxguard.so** is missing in x86 and x86_64 but present in arm64-v8a and armeabi-v7a

**Comment by farimarwat** [comment]
> > do you mean the issue again appeared in 1.3? Could you please share the testing device CPU architecture? or it will be better to send full specification of the device
> 
> Yes it appeared in version 1.3
> 
> Pixel 9a Emulator API Level: 36 ABI/CPU: x86_64
> 
> [@farimarwat](https://github.com/farimarwat) I analysed the generated APK and realized **libmaxguard.so** is missing in x86 and x86_64 but present in arm64-v8a and armeabi-v7a

The library does not support these architectures: x86, x86_64

**Comment by arpitzenmer** [comment]
**OnePlus Devices**: The fact that this issue is observed specifically on OnePlus devices, while not directly indicating a manufacturer-specific bug in Android itself, strongly suggests an ABI mismatch or an incomplete native library delivery for the ABIs prevalent in OnePlus devices . Most modern OnePlus devices are arm64-v8a . If your APK is missing libmaxguard.so for arm64-v8a , then OnePlus devices will likely crash. The recommendation is to prioritize verifying the inclusion of libmaxguard.so for the arm64-v8a architecture in your APK and ensure your build process reliably includes it.

**Android 11 (API 30) Limitations**: Android 11 introduced stricter security and privacy measures, most notably around Scoped Storage. However, these changes primarily affect file system access (e.g., external storage) and package visibility. For native libraries bundled within an application's APK and loaded via System.loadLibrary() , the core dlopen mechanism generally remains consistent. There are no known direct limitations in Android 11 that would specifically cause a `dlopen

**Comment by arpitzenmer** [comment]
Any solution on this?
